# Hospital deployment
- hosts: hosp
  become: yes
  become_method: sudo
  gather_facts: no

  tasks:
    - name: Start Hospital API Service
      systemd:
        name: hospitalapi
        state: started

# Lab deployment
- hosts: lab
  become: yes
  become_method: sudo
  gather_facts: no

  tasks:
    - name: Start Lab API Service
      systemd:
        name: labapi
        state: started

# PDP, PAP... deployment
- hosts: auth
  become: yes
  become_method: sudo
  gather_facts: no

  tasks:
    - name: Start PDP API Service
      systemd:
        name: pdpapi
        state: started