---
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no

  tasks:
    - name: clone repo git
      git:
        repo: "https://github.com/Alex-Pena-Ok/SIRS_Project"
        clone: yes
        dest: '/home/vagrant/project'

    - name: Import maven certificate
      shell: keytool -import -file /home/vagrant/project/vagrant/repo.maven.apache.org -keystore /tmp/mavenKeystore

# Hospital deployment
- hosts: hosp
  become: yes
  become_method: sudo
  gather_facts: no

  tasks:
    - name: Compile Hospital API
      shell: cd /home/vagrant/project/apis/hospital && /opt/maven/bin/mvn package -Djavax.net.ssl.trustStore=/tmp/mavenKeystore
      environment:
        JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64/jre

    - name: Start Hospital API
      shell: cd /home/vagrant/project/apis/hospital/target && java -jar hospital-0.0.1-SNAPSHOT.jar

# Lab deployment
- hosts: lab
  become: yes
  become_method: sudo
  gather_facts: no

  tasks:
    - name: Compile Lab API
      shell: echo "fake"

# PDP, PAP... deployment
- hosts: auth
  become: yes
  become_method: sudo
  gather_facts: no

  tasks:
    - name: Compile Auth Components (PDP, PAP...)
      shell: echo "fake"