---
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no

  tasks:
    - name: clone repo git
      git:
        repo: "https://github.com/Alex-Pena-Ok/SIRS_Project"
        clone: yes
        dest: '/home/vagrant/project'

# Hospital deployment
- hosts: hosp
  become: yes
  become_method: sudo
  gather_facts: no

  tasks:
#    - name: Deploy API Service
#      shell: cd /home/vagrant/project/apis/hospital && mvn clean package

    - name: Start Hospital API Service
      systemd:
        name: hospitalapi
        state: started

# Lab deployment
- hosts: lab
  become: yes
  become_method: sudo
  gather_facts: no

  tasks:
    - name: Compile Lab API
      shell: echo "fake"

# PDP, PAP... deployment
- hosts: auth
  become: yes
  become_method: sudo
  gather_facts: no

  tasks:
    - name: Compile Auth Components (PDP, PAP...)
      shell: echo "fake"