---
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no

  tasks:
    - name: clone repo git
      git:
        repo: "https://github.com/Alex-Pena-Ok/SIRS_Project"
        clone: yes
        dest: '/home/vagrant/project'

# Hospital deployment
- hosts: hosp
  become: yes
  become_method: sudo
  gather_facts: no

  tasks:
    - name: Deploy API to Tomcat
      shell: cp /home/vagrant/project/apis/demo/target/demo-0.0.1-SNAPSHOT.war /var/lib/tomcat7/webapps/demo-0.0.1-SNAPSHOT.war 

# Lab deployment
- hosts: lab
  become: yes
  become_method: sudo
  gather_facts: no

  tasks:
    - name: Compile Lab API
      shell: echo "fake"

# PDP, PAP... deployment
- hosts: auth
  become: yes
  become_method: sudo
  gather_facts: no

  tasks:
    - name: Compile Auth Components (PDP, PAP...)
      shell: echo "fake"