---
# Setup Hospital App & Database
- hosts: hosp
  gather_facts: no

  tasks:

  - name: clone repo git
    git:
      repo: "https://github.com/Alex-Pena-Ok/SIRS_Project"
      clone: yes
      dest: '/home/vagrant/project'
    become: yes
    become_method: sudo

  - name: Drop tables
    become: yes
    become_user: postgres
    shell: psql -U administrator -d projectDb -a -f /home/vagrant/project/db/hospital/dropTables.sql -h 127.0.0.1
    environment:
      PGPASSWORD: administrator

  - name: Create tables
    become: yes
    become_user: postgres
    shell: psql -U administrator -d projectDb -a -f /home/vagrant/project/db/hospital/createTables.sql -h 127.0.0.1
    environment:
      PGPASSWORD: administrator

  - name: Populate tables
    become: yes
    become_user: postgres
    shell: psql -U administrator -d projectDb -a -f /home/vagrant/project/db/hospital/populateTables.sql -h 127.0.0.1
    environment:
      PGPASSWORD: administrator

  # Preencher tabela com script sql correto

  #- name: Compile project
  #  shell: mvn package

  #- name: Starting Hospital API
  #  shell: java -jar api.jar

# Setup Lab's App & Database
- hosts: lab
  gather_facts: no

  tasks:

  - name: clone repo git
    git:
      repo: "https://github.com/Alex-Pena-Ok/SIRS_Project"
      clone: yes
      dest: '/home/vagrant/project'
    become: yes
    become_method: sudo

  - name: Drop tables
    become: yes
    become_user: postgres
    shell: psql -d sirsDb -a -f /home/vagrant/project/db/lab/dropTables.sql

  - name: Create tables
    become: yes
    become_user: postgres
    shell: psql -d sirsDb -a -f /home/vagrant/project/db/lab/createTables.sql

  - name: Populate tables    
    become: yes
    become_user: postgres
    shell: psql -d sirsDb -a -f /home/vagrant/project/db/lab/populateTables.sql

  #- name: Compile project
  #  shell: mvn package

  #- name: Starting Lab API
  #  shell: java -jar api.jar



# Setup the authentication nodes with the access control mechanisms
- hosts: auth
  become: yes
  become_method: sudo
  gather_facts: no

  tasks:

  - name: clone repo git
    git:
      repo: "https://github.com/Alex-Pena-Ok/SIRS_Project/"
      clone: yes
      dest: '/home/vagrant/project'




