---
# Setup Hospital App & Database
- hosts: hosp
  gather_facts: no

  tasks:

  - name: Drop tables
    become: yes
    become_user: postgres
    shell: psql -U administrator -d sirsDb -a -f /home/vagrant/examples/database/dropTables.sql -h 127.0.0.1
    environment:
      PGPASSWORD: administrator

  - name: Create tables
    become: yes
    become_user: postgres
    shell: psql -U administrator -d sirsDb -a -f /home/vagrant/examples/database/createTables.sql -h 127.0.0.1
    environment:
      PGPASSWORD: administrator

  - name: Populate tables
    become: yes
    become_user: postgres
    shell: psql -U administrator -d sirsDb -a -f /home/vagrant/examples/database/populateTables.sql -h 127.0.0.1
    environment:
      PGPASSWORD: administrator


