---
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no

  tasks:

  - name: install ntp
    apt:
      name: ntp
      state: present
      update_cache: yes

  - name: write our ntp.conf
    copy:
      src: /home/vagrant/examples/ntpfiles/ntp.conf
      dest: /etc/ntp.conf
      mode: '0644'
      owner: root
      group: root
    notify: restart ntp

  - name: start ntp
    service:
      name: ntp
      state: started

  - name: install git
    apt:
      name: git
      state: present
      update_cache: yes

  - name: installing repo for Java 8 in Ubuntu
    apt_repository: repo='ppa:openjdk-r/ppa'

  - name: install JDK 8
    apt:
      name: openjdk-8-jdk
      state: present
      update_cache: yes

  - name: clone repo git
    git:
      repo: "https://github.com/Alex-Pena-Ok/SIRS_Project"
      clone: yes
      dest: '/home/vagrant/project'
    become: yes
    become_method: sudo

  - name: download maven
    shell: wget https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz -P /tmp

  - name: extract maven
    shell: tar xf /tmp/apache-maven-3.6.3-bin.tar.gz -C /opt && ln -s /opt/apache-maven-3.6.3 /opt/maven

  - name: configure maven
    shell: sudo cp /home/vagrant/project/vagrant/examples/maven.sh /etc/profile.d/maven.sh && source /etc/profile.d/maven.sh

  - name: Install root CA
    shell: cp /home/vagrant/project/vagrant/examples/certificates/myCA.crt /usr/local/share/ca-certificates/myCA.crt && update-ca-certificates

  handlers:

  - name: restart ntp
    service:
      name: ntp
      state: restarted


# Hospital and Lab MySQL
- hosts: hosp,lab
  remote_user: vagrant
  become: yes
  become_method: sudo
  gather_facts: true

  tasks:
    - name: Ensure bash, OpenSSl, and libssl are the latest versions
      apt: 
        name: ['bash', 'openssl', 'libssl-dev', 'libssl-doc']
        update_cache: true 
        state: latest
      tags: packages

    - name: Install PostgreSQL
      apt: 
        name: ['postgresql', 'postgresql-contrib', 'libpq-dev', 'python-psycopg2'] 
        update_cache: true 
        state: present
      tags: packages

    - name: Ensure the PostgreSQL service is running
      service: name=postgresql state=started enabled=yes

    - name: Create PostgreSQL cluster
      shell: pg_createcluster 9.3 main
      ignore_errors: yes

    - name: Start PostgreSQL cluster
      shell:  /etc/init.d/postgresql start
      ignore_errors: yes

    - name: Create postgres database
      become: true
      become_user: postgres
      postgresql_db:
        name: sirsDb

    - name: Create database user
      become: true
      become_user: postgres
      postgresql_user: db=sirsDb
               name=administrator
               password=administrator
               priv=ALL
               state=present

    - name: Give new user permissions
      become: true
      become_user: postgres
      postgresql_user: name=administrator
               role_attr_flags=SUPERUSER,CREATEDB
               state=present

    - name: Recompile locales configs
      shell: locale-gen pt_PT.UTF-8

    - name: dpkg-reconfigure
      shell: dpkg-reconfigure locales
