---
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no

  tasks:

  - name: install ntp
    apt:
      name: ntp
      state: present
      update_cache: yes

  - name: write our ntp.conf
    copy:
      src: /home/vagrant/examples/ntpfiles/ntp.conf
      dest: /etc/ntp.conf
      mode: '0644'
      owner: root
      group: root
    notify: restart ntp

  - name: start ntp
    systemd:
      name: ntp
      state: started

  - name: install JDK 
    apt:
      name: default-jdk
      state: present
      update_cache: yes

  - name: install maven
    apt:
      name: maven
      state: present
      update_cache: yes

  - name: clone repo git
    git:
      repo: "https://github.com/Alex-Pena-Ok/SIRS_Project"
      clone: yes
      dest: '/home/vagrant/project'
    become: yes
    become_method: sudo

  - name: Install root CA
    shell: cp /home/vagrant/project/vagrant/examples/certificates/myCA.crt /usr/local/share/ca-certificates/myCA.crt && update-ca-certificates

  handlers:

  - name: restart ntp
    service:
      name: ntp
      state: restarted


# Hospital Database (Lab doesnt need a db)
- hosts: hosp
  remote_user: vagrant
  become: yes
  become_method: sudo
  gather_facts: true

  tasks:
    - name: Ensure bash, OpenSSl, and libssl are the latest versions
      apt: 
        name: ['bash', 'openssl', 'libssl-dev', 'libssl-doc']
        update_cache: true 
        state: latest
      tags: packages

    - name: Install PostgreSQL
      apt: 
        name: ['postgresql', 'postgresql-contrib', 'libpq-dev', 'python3-psycopg2'] 
        update_cache: true 
        state: present
      tags: packages

    - name: Ensure the PostgreSQL service is running
      systemd: 
        name: postgresql 
        state: started 
        enabled: yes

    - name: Create postgres database
      become: true
      become_user: postgres
      postgresql_db:
        name: sirsDb

    - name: Create database user
      become: true
      become_user: postgres
      postgresql_user: db=sirsDb
               name=administrator
               password=administrator
               priv=ALL
               state=present

    - name: Give new user permissions
      become: true
      become_user: postgres
      postgresql_user: name=administrator
               role_attr_flags=SUPERUSER,CREATEDB
               state=present


# Hospital API configuration  
- hosts: hosp
  remote_user: vagrant
  become: yes
  become_method: sudo
  gather_facts: true

  tasks:
    - name: Deploy Hospital API Service
      shell: cp /home/vagrant/project/vagrant/examples/hospitalapi.service /etc/systemd/system/hospitalapi.service

    - name: Add Environment Variables
      shell: echo "PGPASSWORD=administrator" >> /etc/profile; echo "PDP_URL='http://192.168.56.12:8081'" >> /etc/profile


# PDP API configuration  
- hosts: auth
  remote_user: vagrant
  become: yes
  become_method: sudo
  gather_facts: true

  tasks:
    - name: Deploy PDP API Service
      shell: cp /home/vagrant/project/vagrant/examples/pdpapi.service /etc/systemd/system/pdpapi.service

    - name: Add Environment Variables
      shell: echo "POLICIES_PATH='/home/vagrant/project/apis/pdp/policies.json'" >> /etc/profile


# LAB API configuration  
- hosts: lab
  remote_user: vagrant
  become: yes
  become_method: sudo
  gather_facts: true

  tasks:
    - name: Deploy Lab API Service
      shell: cp /home/vagrant/project/vagrant/examples/labapi.service /etc/systemd/system/labapi.service
